//! Clap derive surface for `specify source *`. The umbrella `cli.rs`
//! re-exports `SourceAction`.

use std::path::PathBuf;

use clap::Subcommand;
use specify_domain::adapter::SourceOperation;

#[derive(Subcommand)]
pub enum SourceAction {
    /// Resolve a source-adapter manifest by kebab name.
    ///
    /// Probe order: `.specify/.cache/adapters/sources/<name>/adapter.yaml`
    /// (agent-populated cache), then `<project-dir>/adapters/sources/<name>/adapter.yaml`
    /// (in-repo). Emits the resolved directory path plus the
    /// manifest's declared operations.
    ///
    /// `--explain` switches the output to the RFC-27 §D8 fingerprint
    /// chain read from `.specify/.cache/adapters/sources/<name>/index.jsonl`
    /// instead of the manifest summary.
    Resolve {
        /// Kebab-case source-adapter name (e.g. `intent`,
        /// `documentation`, `code-typescript`, `screenshots`).
        name: String,
        /// Project directory containing `.specify/` (defaults to the
        /// current directory).
        #[arg(long, default_value = ".")]
        project_dir: PathBuf,
        /// Print the fingerprint chain from
        /// `.specify/.cache/adapters/sources/<name>/index.jsonl` instead of the
        /// manifest summary.
        #[arg(long)]
        explain: bool,
    },
    /// RFC-27 §D8 cache helpers — fingerprint computation, lookup,
    /// write. Skills call these between adapter brief invocations.
    Cache {
        #[command(subcommand)]
        action: SourceCacheAction,
    },
}

/// `specify source cache *` subcommands.
#[derive(Subcommand)]
pub enum SourceCacheAction {
    /// Compute the fingerprint for one `enumerate`/`extract` lookup
    /// and report whether the cache hits. Emits the matching
    /// `slice.extract.cache-hit` or `slice.extract.cache-miss` journal
    /// event.
    Lookup {
        #[command(flatten)]
        fp: CacheFingerprintArgs,
    },
    /// Write a cache entry (artifact bytes + `fingerprint.json` + one
    /// row appended to `index.jsonl`). Skips the directory body when
    /// the adapter manifest declares `cache: opt-out`.
    Write {
        #[command(flatten)]
        fp: CacheFingerprintArgs,
        /// Path to the artifact bytes (`evidence.yaml` or
        /// `candidate-set.md`) the agent generated by running the
        /// adapter brief.
        #[arg(long)]
        payload: PathBuf,
    },
}

/// Shared positional + flag set for the RFC-27 §D8 fingerprint
/// surface. `lookup` and `write` carry the same five-input record
/// (RFC-27 §D8) plus the slice / source-key / operation triple that
/// names the cache lane.
#[derive(clap::Args, Clone)]
pub struct CacheFingerprintArgs {
    /// Kebab-case source-adapter name (positional; matches the
    /// directory under `adapters/sources/` or `.specify/.cache/adapters/sources/`).
    pub adapter: String,
    /// Project directory containing `.specify/` (defaults to the
    /// current directory).
    #[arg(long, default_value = ".")]
    pub project_dir: PathBuf,
    /// Slice id under `plan.yaml.slices[].name`.
    #[arg(long)]
    pub slice: String,
    /// Source key from `plan.yaml.sources.<key>` — names the cache
    /// lane shared across runs.
    #[arg(long)]
    pub source_key: String,
    /// Source-adapter operation that drove the call (`enumerate` or
    /// `extract`).
    #[arg(long, value_enum)]
    pub operation: SourceOperation,
    /// Path-style source binding — canonicalised before hashing.
    /// Mutually exclusive with `--source-value` (clap enforces).
    #[arg(long, conflicts_with = "source_value", required_unless_present = "source_value")]
    pub source_path: Option<PathBuf>,
    /// Value-style source binding — sha256-hashed before keying.
    /// Mutually exclusive with `--source-path`.
    #[arg(long)]
    pub source_value: Option<String>,
    /// Candidate id (RFC-27 §D8 fingerprint input #5). Required for
    /// `--operation extract`; absent on `enumerate`.
    #[arg(long)]
    pub candidate: Option<String>,
}
