//! Write planner that decides whether to create, replace, or leave
//! `AGENTS.md` alone, splicing the renderer's generated bytes into any
//! operator-authored prefix and suffix that [`super::parse`] surfaced.

use super::parse::{FenceError, parse_document};

/// Kind of write the planner selected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::commands::context) enum WriteDisposition {
    /// `AGENTS.md` was absent, so the full generated document should be created.
    Create,
    /// `AGENTS.md` was unfenced and `--force` allowed a full rewrite.
    ForceRewriteUnfenced,
    /// `AGENTS.md` was fenced, so only the generated block should be replaced.
    ReplaceFencedBlock,
    /// The planned output is byte-identical to the existing `AGENTS.md`.
    Unchanged,
}

/// Pure write-plan result for `AGENTS.md`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::commands::context) struct PlannedWrite {
    /// Complete bytes that should be persisted to `AGENTS.md`.
    pub(in crate::commands::context) bytes: Vec<u8>,
    /// Policy decision used to produce `bytes`.
    pub(in crate::commands::context) disposition: WriteDisposition,
}

/// Compose final `AGENTS.md` bytes according to the context fence policy.
pub(in crate::commands::context) fn plan_agents_write(
    existing: Option<&[u8]>, generated_document: &[u8], force: bool,
) -> Result<PlannedWrite, FenceError> {
    let generated =
        parse_document(generated_document)?.ok_or(FenceError::GeneratedDocumentMissingFences)?;

    let Some(existing) = existing else {
        return Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::Create,
        });
    };

    match parse_document(existing)? {
        Some(current) => {
            let mut bytes = Vec::with_capacity(
                current.prefix().len() + generated.generated_block().len() + current.suffix().len(),
            );
            bytes.extend_from_slice(current.prefix());
            bytes.extend_from_slice(generated.generated_block());
            bytes.extend_from_slice(current.suffix());
            let disposition = if bytes == existing {
                WriteDisposition::Unchanged
            } else {
                WriteDisposition::ReplaceFencedBlock
            };
            Ok(PlannedWrite { bytes, disposition })
        }
        None if force => Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::ForceRewriteUnfenced,
        }),
        None => Err(FenceError::ExistingUnfencedAgentsMd),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const GENERATED: &[u8] = b"# demo - Agent Instructions\n\n<!-- specify:context begin\nfingerprint: sha256:new\ngenerated-by: specify 0.2.0\n-->\n\n## Runtime\n- new\n\n<!-- specify:context end -->\n";

    fn fenced_existing() -> Vec<u8> {
        b"# hand title\n\n<!-- specify:context begin\nfingerprint: sha256:old\n-->\n\nold body\n\n<!-- specify:context end -->\n\noperator notes\n".to_vec()
    }

    #[test]
    fn writer_creates_full_document_when_agents_is_absent() {
        let planned = plan_agents_write(None, GENERATED, false).expect("plan ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::Create);
    }

    #[test]
    fn writer_refuses_existing_unfenced_document_without_force() {
        let err = plan_agents_write(Some(b"# hand-authored\n"), GENERATED, false)
            .expect_err("unfenced must refuse");

        assert_eq!(err, FenceError::ExistingUnfencedAgentsMd);
    }

    #[test]
    fn writer_rewrites_existing_unfenced_document_with_force() {
        let planned = plan_agents_write(Some(b"# hand-authored\n"), GENERATED, true)
            .expect("force rewrite ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::ForceRewriteUnfenced);
    }

    #[test]
    fn writer_replaces_only_generated_block() {
        let existing = fenced_existing();
        let planned = plan_agents_write(Some(&existing), GENERATED, false).expect("plan ok");
        let expected = b"# hand title\n\n<!-- specify:context begin\nfingerprint: sha256:new\ngenerated-by: specify 0.2.0\n-->\n\n## Runtime\n- new\n\n<!-- specify:context end -->\n\noperator notes\n";

        assert_eq!(planned.bytes, expected);
        assert_eq!(planned.disposition, WriteDisposition::ReplaceFencedBlock);
    }

    #[test]
    fn writer_preserves_non_utf8_surrounding_bytes() {
        let existing = [
            b"prefix ".as_slice(),
            &[0xff, b'\n'],
            b"<!-- specify:context begin\nfingerprint: sha256:old\n-->\nold\n<!-- specify:context end -->",
            &[b'\n', 0xfe],
        ]
        .concat();
        let planned = plan_agents_write(Some(&existing), GENERATED, false).expect("plan ok");

        assert!(planned.bytes.starts_with(b"prefix \xff\n<!-- specify:context begin"));
        assert!(planned.bytes.ends_with(b"\n\xfe"));
    }

    #[test]
    fn writer_reports_unchanged_when_bytes_match() {
        let planned = plan_agents_write(Some(GENERATED), GENERATED, false).expect("plan ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::Unchanged);
    }

    #[test]
    fn writer_requires_generated_document_to_be_fenced() {
        let err = plan_agents_write(None, b"# generated but unfenced\n", false)
            .expect_err("generated document without fences must fail");

        assert_eq!(err, FenceError::GeneratedDocumentMissingFences);
    }
}
