doc-valid-idents = [
  "GitHub",
  "OAuth",
  "OpenTelemetry",
  "WebAssembly",
  "YAML",
]

allowed-duplicate-crates = [
  "base64",
  "core-foundation",
  "darling",
  "darling_core",
  "darling_macro",
  "embedded-io",
  "fixedbitset",
  "foldhash",
  "getrandom",
  "hashbrown",
  "heck",
  "indexmap",
  "lazy_static",
  "linux-raw-sys",
  "petgraph",
  "r-efi",
  "rand",
  "rand_chacha",
  "rand_core",
  "reqwest",
  "rustix",
  "schemars",
  "security-framework",
  "strum",
  "strum_macros",
  "thiserror",
  "thiserror-impl",
  "toml_datetime",
  "toml_edit",
  "wasm-encoder",
  "wasm-streams",
  "wasmparser",
  "wasmprinter",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
  "wit-bindgen",
  "wit-parser",
  "winnow",
]
