//! Embedded JSON Schemas.
//!
//! Each constant is the verbatim contents of a file under
//! `specify-cli/schemas/` baked into the binary at compile time. See
//! `ResolvedRules` export contract and §"Structured lint finding
//! schema" for the standards-layer schemas; the workflow schemas are
//! pinned by the workflow contract under `docs/standards/workflow.md`.

/// Schema for the shared adapter manifest envelope (axis-agnostic
/// `adapter.yaml` fields validated before the per-axis split).
pub const ADAPTER_JSON_SCHEMA: &str = include_str!("../../../schemas/adapter.schema.json");

/// Schema for a source-axis adapter manifest (`survey` / `extract`).
pub const SOURCE_JSON_SCHEMA: &str = include_str!("../../../schemas/source.schema.json");

/// Schema for a target-axis adapter manifest (`shape` / `build` / `merge`).
pub const TARGET_JSON_SCHEMA: &str = include_str!("../../../schemas/target.schema.json");

/// Schema for a WASI tool manifest (`tool.schema.json`) declared by an
/// adapter under `tools[]`.
pub const TOOL_JSON_SCHEMA: &str = include_str!("../../../schemas/tool.schema.json");

/// Schema for a fetched WASI tool sidecar metadata file
/// (`<artifact>.sha256` companion manifest).
pub const TOOL_SIDECAR_JSON_SCHEMA: &str =
    include_str!("../../../schemas/tool-sidecar.schema.json");

/// Schema for `plan.yaml` (workflow contract — `slices[].sources[]`
/// bindings, `target`, slice-level `divergence` enum).
pub const PLAN_JSON_SCHEMA: &str = include_str!("../../../schemas/plan/plan.schema.json");

/// Schema for per-source `Evidence` files under
/// `.specify/slices/<name>/evidence/`.
pub const EVIDENCE_JSON_SCHEMA: &str = include_str!("../../../schemas/evidence.schema.json");

/// Schema for a single `Lead` block under `## Lead inventory` in
/// `discovery.md`. The `survey` operation validates each produced lead
/// against this shape before `Discovery::merge_survey` makes it visible.
pub const LEAD_JSON_SCHEMA: &str = include_str!("../../../schemas/discovery/lead.schema.json");

/// Schema for the lead-reconciliation request/response envelope
/// (`specify plan propose`). A closed `kind: request | response`
/// `oneOf` discriminates the dry-run catalog from the agent grouping.
pub const PROPOSAL_JSON_SCHEMA: &str =
    include_str!("../../../schemas/discovery/proposal.schema.json");

/// Schema for the single slice `model.yaml`.
///
/// One schema validates both the agent synthesis-response `model` and
/// the persisted file: kernel-owned and header fields are optional so
/// the kernel re-derives/stamps them on projection. Provenance is
/// carried inline; the provenance view is projected on demand.
pub const SLICE_MODEL_JSON_SCHEMA: &str = include_str!("../../../schemas/slice/model.schema.json");

/// Schema for the agent synthesis-response envelope.
///
/// Validates the `kind: response` wire the agent-led synthesis step
/// returns. Its `model` property `$ref`s `model.schema.json` by a
/// relative URI, so the two schemas are registered together (the model
/// schema pinned under its `$id`) for the ref to resolve.
pub const SYNTHESIS_JSON_SCHEMA: &str =
    include_str!("../../../schemas/slice/synthesis.schema.json");

/// Schema for the provenance projection emitted on demand by
/// `specify slice provenance`. Audit-only and projected from
/// `model.yaml`; not a persisted file.
pub const PROVENANCE_JSON_SCHEMA: &str =
    include_str!("../../../schemas/slice/provenance.schema.json");

/// Schema for a Decision Record front-matter block.
///
/// One schema validates both the slice-authored form under
/// `.specify/slices/<slice>/decisions/<slug>.md` and the promoted
/// baseline form under `.specify/decisions/DEC-NNNN-<slug>.md`:
/// engine-stamped `id` / `slice` / `date` / `superseded-by` are
/// optional here so the one shape serves both. `specify slice validate`
/// gates the slice form; `specify slice merge` stamps and promotes.
pub const DECISION_JSON_SCHEMA: &str = include_str!("../../../schemas/decision.schema.json");

/// Schema for `.specify/topology.lock`.
///
/// The committed projection of each member project's `project.yaml`
/// topology facets, regenerated by `specify workspace sync`.
/// Hub plan-time topology reads the cache rather than `registry.yaml`.
pub const TOPOLOGY_LOCK_JSON_SCHEMA: &str =
    include_str!("../../../schemas/topology-lock.schema.json");

/// Schema for `components.yaml`, the agent-inferred, operator-reviewable
/// design-system component catalog.
pub const COMPONENTS_JSON_SCHEMA: &str =
    include_str!("../../../schemas/design-system/components.schema.json");

/// Schema for `parts.yaml`, the operator-authored component parts input.
///
/// Operator parts: each part declares an authoritative composition `group`
/// fragment that seeds inference with naming and promotion authority.
pub const PARTS_JSON_SCHEMA: &str =
    include_str!("../../../schemas/design-system/parts.schema.json");

/// Schema for the `specify rules export` payload — the resolved rules
/// tree consumed by lint tooling. See `ResolvedRules` export contract.
pub const RESOLVED_RULES_JSON_SCHEMA: &str =
    include_str!("../../../schemas/rules/resolved.schema.json");

/// Schema for a single rule frontmatter block. See the rule file shape contract.
pub const RULE_JSON_SCHEMA: &str = include_str!("../../../schemas/rules/rule.schema.json");

/// Schema for the neutral `Diagnostic` wire shape produced by every
/// check surface (lint and validate alike) and validated at the
/// diagnostic boundary. See the structured diagnostic schema.
pub const DIAGNOSTIC_JSON_SCHEMA: &str =
    include_str!("../../../schemas/diagnostics/diagnostic.schema.json");

/// Schema for the v1 `WorkspaceModel` envelope produced once per
/// `specify lint` invocation.
///
/// See the `WorkspaceModel` schema and schema-location contract; the
/// `version: 1` discriminant pins the v1 shape defined here.
pub const WORKSPACE_MODEL_JSON_SCHEMA: &str =
    include_str!("../../../schemas/lint/workspace-model.schema.json");

/// Schema for the `DiagnosticReport` envelope (`{ version, summary, findings }`).
///
/// Validated before stdout emit by every diagnostic surface
/// (`specify lint --format json` and the workflow-gating validate
/// surface alike). The `findings[]` element shape lives in
/// [`DIAGNOSTIC_JSON_SCHEMA`] and is wired via a relative
/// `diagnostic.schema.json` `$ref`.
pub const DIAGNOSTIC_REPORT_JSON_SCHEMA: &str =
    include_str!("../../../schemas/diagnostics/diagnostic-report.schema.json");

/// Schema for `SKILL.md` YAML frontmatter (framework authoring).
pub const SKILL_JSON_SCHEMA: &str = include_str!("../../../schemas/authoring/skill.schema.json");

/// Schema for scenario-pack YAML frontmatter (framework authoring).
pub const SCENARIO_JSON_SCHEMA: &str =
    include_str!("../../../schemas/authoring/scenario.schema.json");

/// Schema for `.cursor-plugin/marketplace.json` (framework authoring).
pub const MARKETPLACE_JSON_SCHEMA: &str =
    include_str!("../../../schemas/authoring/marketplace.schema.json");

/// Schema for `Specify.toml` framework authoring config.
pub const FRAMEWORK_JSON_SCHEMA: &str =
    include_str!("../../../schemas/authoring/framework.schema.json");

/// Schema for the per-slice target build request.
///
/// The closed-shape request `specify slice build` hands to a target
/// adapter. Keyed on `(slice, target)`, but the payload omits `target`,
/// `execution`, brief paths, and `model.yaml`; target-specific inputs
/// grow through the explicit `inputs.artifacts.additional` list.
pub const BUILD_REQUEST_JSON_SCHEMA: &str =
    include_str!("../../../schemas/target/build-request.schema.json");

/// Schema for the per-slice target build report.
///
/// The closed-shape report a target adapter returns to `specify slice
/// build`. Its `findings[]` element shape lives in
/// [`DIAGNOSTIC_JSON_SCHEMA`] and is wired via a relative
/// `../diagnostics/diagnostic.schema.json` `$ref`.
pub const BUILD_REPORT_JSON_SCHEMA: &str =
    include_str!("../../../schemas/target/build-report.schema.json");

/// Schema for the `specify contract dump` payload — the machine-readable
/// CLI contract (verb tree, exit codes, error discriminants, journal
/// event ids, embedded schema paths).
pub const CONTRACT_DUMP_JSON_SCHEMA: &str =
    include_str!("../../../schemas/contract/dump.schema.json");

/// Every embedded schema as `(constant-name, schemas/-relative path,
/// body)`, in declaration order.
///
/// The canonical inventory behind two consumers: the
/// `embedded_schemas_match_on_disk_sources` parity test (each body must
/// byte-match its on-disk source) and `specify contract dump` (which
/// publishes the relative paths). Add new embedded constants here in
/// the same change that declares them.
pub const EMBEDDED_SCHEMAS: &[(&str, &str, &str)] = &[
    ("ADAPTER_JSON_SCHEMA", "schemas/adapter.schema.json", ADAPTER_JSON_SCHEMA),
    ("SOURCE_JSON_SCHEMA", "schemas/source.schema.json", SOURCE_JSON_SCHEMA),
    ("TARGET_JSON_SCHEMA", "schemas/target.schema.json", TARGET_JSON_SCHEMA),
    ("TOOL_JSON_SCHEMA", "schemas/tool.schema.json", TOOL_JSON_SCHEMA),
    ("TOOL_SIDECAR_JSON_SCHEMA", "schemas/tool-sidecar.schema.json", TOOL_SIDECAR_JSON_SCHEMA),
    ("PLAN_JSON_SCHEMA", "schemas/plan/plan.schema.json", PLAN_JSON_SCHEMA),
    ("EVIDENCE_JSON_SCHEMA", "schemas/evidence.schema.json", EVIDENCE_JSON_SCHEMA),
    ("LEAD_JSON_SCHEMA", "schemas/discovery/lead.schema.json", LEAD_JSON_SCHEMA),
    ("PROPOSAL_JSON_SCHEMA", "schemas/discovery/proposal.schema.json", PROPOSAL_JSON_SCHEMA),
    ("SLICE_MODEL_JSON_SCHEMA", "schemas/slice/model.schema.json", SLICE_MODEL_JSON_SCHEMA),
    ("SYNTHESIS_JSON_SCHEMA", "schemas/slice/synthesis.schema.json", SYNTHESIS_JSON_SCHEMA),
    ("PROVENANCE_JSON_SCHEMA", "schemas/slice/provenance.schema.json", PROVENANCE_JSON_SCHEMA),
    ("DECISION_JSON_SCHEMA", "schemas/decision.schema.json", DECISION_JSON_SCHEMA),
    ("TOPOLOGY_LOCK_JSON_SCHEMA", "schemas/topology-lock.schema.json", TOPOLOGY_LOCK_JSON_SCHEMA),
    (
        "COMPONENTS_JSON_SCHEMA",
        "schemas/design-system/components.schema.json",
        COMPONENTS_JSON_SCHEMA,
    ),
    ("PARTS_JSON_SCHEMA", "schemas/design-system/parts.schema.json", PARTS_JSON_SCHEMA),
    (
        "RESOLVED_RULES_JSON_SCHEMA",
        "schemas/rules/resolved.schema.json",
        RESOLVED_RULES_JSON_SCHEMA,
    ),
    ("RULE_JSON_SCHEMA", "schemas/rules/rule.schema.json", RULE_JSON_SCHEMA),
    (
        "DIAGNOSTIC_JSON_SCHEMA",
        "schemas/diagnostics/diagnostic.schema.json",
        DIAGNOSTIC_JSON_SCHEMA,
    ),
    (
        "DIAGNOSTIC_REPORT_JSON_SCHEMA",
        "schemas/diagnostics/diagnostic-report.schema.json",
        DIAGNOSTIC_REPORT_JSON_SCHEMA,
    ),
    (
        "WORKSPACE_MODEL_JSON_SCHEMA",
        "schemas/lint/workspace-model.schema.json",
        WORKSPACE_MODEL_JSON_SCHEMA,
    ),
    ("SKILL_JSON_SCHEMA", "schemas/authoring/skill.schema.json", SKILL_JSON_SCHEMA),
    ("SCENARIO_JSON_SCHEMA", "schemas/authoring/scenario.schema.json", SCENARIO_JSON_SCHEMA),
    (
        "MARKETPLACE_JSON_SCHEMA",
        "schemas/authoring/marketplace.schema.json",
        MARKETPLACE_JSON_SCHEMA,
    ),
    ("FRAMEWORK_JSON_SCHEMA", "schemas/authoring/framework.schema.json", FRAMEWORK_JSON_SCHEMA),
    (
        "BUILD_REQUEST_JSON_SCHEMA",
        "schemas/target/build-request.schema.json",
        BUILD_REQUEST_JSON_SCHEMA,
    ),
    (
        "BUILD_REPORT_JSON_SCHEMA",
        "schemas/target/build-report.schema.json",
        BUILD_REPORT_JSON_SCHEMA,
    ),
    ("CONTRACT_DUMP_JSON_SCHEMA", "schemas/contract/dump.schema.json", CONTRACT_DUMP_JSON_SCHEMA),
];
