//! Embedded JSON Schemas.
//!
//! Each constant is the verbatim contents of a file under
//! `specify-cli/schemas/` baked into the binary at compile time. See
//! `ResolvedRules` export contract and §"Structured lint finding
//! schema" for the standards-layer schemas; the workflow schemas are
//! pinned by the workflow contract under `docs/standards/workflow.md`.

/// Schema for the shared adapter manifest envelope (axis-agnostic
/// `adapter.yaml` fields validated before the per-axis split).
pub const ADAPTER_JSON_SCHEMA: &str = include_str!("../../../schemas/adapter.schema.json");

/// Schema for a source-axis adapter manifest (`survey` / `extract`).
pub const SOURCE_JSON_SCHEMA: &str = include_str!("../../../schemas/source.schema.json");

/// Schema for a target-axis adapter manifest (`shape` / `build` / `merge`).
pub const TARGET_JSON_SCHEMA: &str = include_str!("../../../schemas/target.schema.json");

/// Schema for a WASI tool manifest (`tool.schema.json`) declared by an
/// adapter under `tools[]`.
pub const TOOL_JSON_SCHEMA: &str = include_str!("../../../schemas/tool.schema.json");

/// Schema for a fetched WASI tool sidecar metadata file
/// (`<artifact>.sha256` companion manifest).
pub const TOOL_SIDECAR_JSON_SCHEMA: &str =
    include_str!("../../../schemas/tool-sidecar.schema.json");

/// Schema for `plan.yaml` (workflow contract — `slices[].sources[]`
/// bindings, `target`, slice-level `divergence` enum).
pub const PLAN_JSON_SCHEMA: &str = include_str!("../../../schemas/plan/plan.schema.json");

/// Schema for per-source `Evidence` files under
/// `.specify/slices/<name>/evidence/`.
pub const EVIDENCE_JSON_SCHEMA: &str = include_str!("../../../schemas/evidence.schema.json");

/// Schema for a single `Lead` block under `## Lead inventory` in
/// `discovery.md`. The `survey` operation validates each produced lead
/// against this shape before `Discovery::merge_survey` makes it visible.
pub const LEAD_JSON_SCHEMA: &str = include_str!("../../../schemas/discovery/lead.schema.json");

/// Schema for the lead-reconciliation request/response envelope
/// (`specrun plan propose`). A closed `kind: request | response`
/// `oneOf` discriminates the dry-run catalog from the agent grouping.
pub const PROPOSAL_JSON_SCHEMA: &str =
    include_str!("../../../schemas/discovery/proposal.schema.json");

/// Schema for the single slice `model.yaml` (RFC-29 M2b).
///
/// One schema validates both the agent synthesis-response `model` and
/// the persisted file: kernel-owned and header fields are optional so
/// the kernel re-derives/stamps them on projection. Provenance is
/// carried inline; the provenance view is projected on demand.
pub const SLICE_MODEL_JSON_SCHEMA: &str = include_str!("../../../schemas/slice/model.schema.json");

/// Schema for the agent synthesis-response envelope (RFC-29 M2b).
///
/// Validates the `kind: response` wire the agent-led synthesis step
/// returns. Its `model` property `$ref`s `model.schema.json` by a
/// relative URI, so the two schemas are registered together (the model
/// schema pinned under its `$id`) for the ref to resolve.
pub const SYNTHESIS_JSON_SCHEMA: &str =
    include_str!("../../../schemas/slice/synthesis.schema.json");

/// Schema for the provenance projection emitted on demand by
/// `specrun slice provenance`. Audit-only and projected from
/// `model.yaml`; not a persisted file.
pub const PROVENANCE_JSON_SCHEMA: &str =
    include_str!("../../../schemas/slice/provenance.schema.json");

/// Schema for a Decision Record front-matter block (RFC-36).
///
/// One schema validates both the slice-authored form under
/// `.specify/slices/<slice>/decisions/<slug>.md` and the promoted
/// baseline form under `.specify/decisions/DEC-NNNN-<slug>.md`:
/// engine-stamped `id` / `slice` / `date` / `superseded-by` are
/// optional here so the one shape serves both. `specrun slice validate`
/// gates the slice form; `specrun slice merge` stamps and promotes.
pub const DECISION_JSON_SCHEMA: &str = include_str!("../../../schemas/decision.schema.json");

/// Schema for `.specify/topology.lock`.
///
/// The committed projection of each member project's `project.yaml`
/// topology facets, regenerated by `specrun workspace sync` (RFC-36).
/// Hub plan-time topology reads the cache rather than `registry.yaml`.
pub const TOPOLOGY_LOCK_JSON_SCHEMA: &str =
    include_str!("../../../schemas/topology-lock.schema.json");

/// Schema for `components.yaml`, the operator-curated design-system
/// component catalog.
pub const COMPONENTS_JSON_SCHEMA: &str =
    include_str!("../../../schemas/design-system/components.schema.json");

/// Schema for the `specrun rules export` payload — the resolved rules
/// tree consumed by lint tooling. See `ResolvedRules` export contract.
pub const RESOLVED_RULES_JSON_SCHEMA: &str =
    include_str!("../../../schemas/rules/resolved.schema.json");

/// Schema for a single rule frontmatter block. See the rule file shape contract.
pub const RULE_JSON_SCHEMA: &str = include_str!("../../../schemas/rules/rule.schema.json");

/// Schema for the neutral `Diagnostic` wire shape produced by every
/// check surface (lint and validate alike) and validated at the
/// diagnostic boundary. See the structured diagnostic schema.
pub const DIAGNOSTIC_JSON_SCHEMA: &str =
    include_str!("../../../schemas/diagnostics/diagnostic.schema.json");

/// Schema for the v1 `WorkspaceModel` envelope produced once per
/// `specrun lint` invocation.
///
/// See the `WorkspaceModel` schema and schema-location contract; the
/// `version: 1` discriminant pins the v1 shape defined here.
pub const WORKSPACE_MODEL_JSON_SCHEMA: &str =
    include_str!("../../../schemas/lint/workspace-model.schema.json");

/// Schema for the `DiagnosticReport` envelope (`{ version, summary, findings }`).
///
/// Validated before stdout emit by every diagnostic surface
/// (`specrun lint --format json` and the workflow-gating validate
/// surface alike). The `findings[]` element shape lives in
/// [`DIAGNOSTIC_JSON_SCHEMA`] and is wired via a relative
/// `diagnostic.schema.json` `$ref`.
pub const DIAGNOSTIC_REPORT_JSON_SCHEMA: &str =
    include_str!("../../../schemas/diagnostics/diagnostic-report.schema.json");

/// Schema for `SKILL.md` YAML frontmatter (framework authoring).
pub const SKILL_JSON_SCHEMA: &str = include_str!("../../../schemas/authoring/skill.schema.json");

/// Schema for scenario-pack YAML frontmatter (framework authoring).
pub const SCENARIO_JSON_SCHEMA: &str =
    include_str!("../../../schemas/authoring/scenario.schema.json");

/// Schema for `.cursor-plugin/marketplace.json` (framework authoring).
pub const MARKETPLACE_JSON_SCHEMA: &str =
    include_str!("../../../schemas/authoring/marketplace.schema.json");

/// Schema for the per-slice target build request (RFC-29d D6).
///
/// The closed-shape request `specrun slice build` hands to a target
/// adapter. Keyed on `(slice, target)`, but the payload omits `target`,
/// `execution`, brief paths, and `model.yaml`; target-specific inputs
/// grow through the explicit `inputs.artifacts.additional` list.
pub const BUILD_REQUEST_JSON_SCHEMA: &str =
    include_str!("../../../schemas/target/build-request.schema.json");

/// Schema for the per-slice target build report (RFC-29d D6).
///
/// The closed-shape report a target adapter returns to `specrun slice
/// build`. Its `findings[]` element shape lives in
/// [`DIAGNOSTIC_JSON_SCHEMA`] and is wired via a relative
/// `../diagnostics/diagnostic.schema.json` `$ref`.
pub const BUILD_REPORT_JSON_SCHEMA: &str =
    include_str!("../../../schemas/target/build-report.schema.json");
