//! Byte-preserving parser and write planner for fenced `AGENTS.md` context.
//!
//! The renderer owns generated bytes. This module owns the file-shape contract:
//! identify the generated context block strictly, preserve operator-authored
//! bytes around it, and refuse to replace an unfenced file unless requested.
//!
//! [`parse`] decodes a candidate document into a `FencedDocument` (or a
//! typed [`FenceError`]); [`render`] composes the final write plan.

mod parse;
mod render;

pub(super) use parse::{FenceError, parse_document};
pub(super) use render::{WriteDisposition, plan_agents_write};
