//! Byte-preserving parser and write planner for fenced `AGENTS.md` context.
//!
//! The renderer owns generated bytes. This module owns the file-shape contract:
//! identify the generated context block strictly, preserve operator-authored
//! bytes around it, and refuse to replace an unfenced file unless requested.

use std::collections::BTreeMap;

const OPEN_LINE: &[u8] = b"<!-- specify:context begin\n";
const OPEN_MARKER: &[u8] = b"<!-- specify:context begin";
const OPEN_END_LINE: &[u8] = b"-->";
const CLOSE_MARKER: &[u8] = b"<!-- specify:context end -->";

/// Parsed representation of a single fenced context block.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct FencedDocument<'a> {
    source: &'a [u8],
    block_start: usize,
    body_start: usize,
    close_start: usize,
    close_end: usize,
    metadata: BTreeMap<String, String>,
}

impl<'a> FencedDocument<'a> {
    /// Bytes before the opening fence.
    #[must_use]
    pub(super) fn prefix(&self) -> &'a [u8] {
        &self.source[..self.block_start]
    }

    /// Bytes from the opening fence through the closing fence.
    #[must_use]
    pub(super) fn generated_block(&self) -> &'a [u8] {
        &self.source[self.block_start..self.close_end]
    }

    /// Bytes between the completed opening fence and the closing fence.
    #[must_use]
    pub(super) fn body(&self) -> &'a [u8] {
        &self.source[self.body_start..self.close_start]
    }

    /// Bytes after the closing fence.
    #[must_use]
    pub(super) fn suffix(&self) -> &'a [u8] {
        &self.source[self.close_end..]
    }

    /// Opening-fence metadata parsed as deterministic key order.
    #[cfg(test)]
    #[must_use]
    pub(super) const fn metadata(&self) -> &BTreeMap<String, String> {
        &self.metadata
    }
}

/// Reason a fenced document could not be parsed or planned.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) enum FenceError {
    /// The existing `AGENTS.md` has no context fences and `--force` was not set.
    ExistingUnfencedAgentsMd,
    /// The generated document supplied by the renderer had no valid context fences.
    GeneratedDocumentMissingFences,
    /// More than one opening fence was present, making replacement ambiguous.
    MultipleOpeningFences,
    /// More than one closing fence was present, making replacement ambiguous.
    MultipleClosingFences,
    /// The opening fence was found but its metadata terminator was missing.
    MissingOpeningFenceTerminator,
    /// The opening fence terminated before any key-value metadata lines.
    MissingOpeningFenceMetadata,
    /// The opening fence was found but the matching closing fence was missing.
    MissingClosingFence,
    /// A metadata key appeared more than once in the opening fence.
    DuplicateMetadataKey(String),
    /// A metadata line was not strict `key: value` ASCII.
    InvalidMetadataLine(String),
}

impl std::fmt::Display for FenceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ExistingUnfencedAgentsMd => f.write_str(
                "context-existing-unfenced-agents-md: AGENTS.md exists without Specify context \
                 fences; rerun with --force to rewrite it",
            ),
            Self::GeneratedDocumentMissingFences => f.write_str(
                "context-generated-document-missing-fences: generated AGENTS.md content must \
                 contain a Specify context fence",
            ),
            Self::MultipleOpeningFences => {
                f.write_str("context-malformed-fences: multiple opening fences found")
            }
            Self::MultipleClosingFences => {
                f.write_str("context-malformed-fences: multiple closing fences found")
            }
            Self::MissingOpeningFenceTerminator => f.write_str(
                "context-malformed-fences: opening context fence is missing its `-->` line",
            ),
            Self::MissingOpeningFenceMetadata => {
                f.write_str("context-malformed-fences: opening context fence must include metadata")
            }
            Self::MissingClosingFence => {
                f.write_str("context-malformed-fences: closing context fence not found")
            }
            Self::DuplicateMetadataKey(key) => {
                write!(f, "context-malformed-fences: duplicate opening-fence metadata key `{key}`")
            }
            Self::InvalidMetadataLine(line) => {
                write!(f, "context-malformed-fences: invalid opening-fence metadata line `{line}`")
            }
        }
    }
}

impl std::error::Error for FenceError {}

/// Kind of write the planner selected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum WriteDisposition {
    /// `AGENTS.md` was absent, so the full generated document should be created.
    Create,
    /// `AGENTS.md` was unfenced and `--force` allowed a full rewrite.
    ForceRewriteUnfenced,
    /// `AGENTS.md` was fenced, so only the generated block should be replaced.
    ReplaceFencedBlock,
    /// The planned output is byte-identical to the existing `AGENTS.md`.
    Unchanged,
}

/// Pure write-plan result for `AGENTS.md`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct PlannedWrite {
    /// Complete bytes that should be persisted to `AGENTS.md`.
    pub(super) bytes: Vec<u8>,
    /// Policy decision used to produce `bytes`.
    pub(super) disposition: WriteDisposition,
}

/// Parse a document that may contain a Specify context fence.
///
/// Returns `Ok(None)` only when no context fence markers are present at all.
pub(super) fn parse_document(bytes: &[u8]) -> Result<Option<FencedDocument<'_>>, FenceError> {
    let Some(block_start) = find_subslice(bytes, OPEN_MARKER, 0) else {
        if find_valid_closing_fences(bytes, 0)?.is_empty() {
            return Ok(None);
        }
        return Err(FenceError::MissingOpeningFenceTerminator);
    };

    if find_subslice(bytes, OPEN_MARKER, block_start + OPEN_MARKER.len()).is_some() {
        return Err(FenceError::MultipleOpeningFences);
    }
    if !bytes[block_start..].starts_with(OPEN_LINE) {
        return Err(FenceError::MissingOpeningFenceTerminator);
    }

    let metadata_start = block_start + OPEN_LINE.len();
    let (metadata, body_start) = parse_opening_metadata(bytes, metadata_start)?;
    let closing_fences = find_valid_closing_fences(bytes, body_start)?;
    match closing_fences.as_slice() {
        [] => Err(FenceError::MissingClosingFence),
        [close_start] => Ok(Some(FencedDocument {
            source: bytes,
            block_start,
            body_start,
            close_start: *close_start,
            close_end: close_start + CLOSE_MARKER.len(),
            metadata,
        })),
        [_, ..] => Err(FenceError::MultipleClosingFences),
    }
}

/// Compose final `AGENTS.md` bytes according to the context fence policy.
pub(super) fn plan_agents_write(
    existing: Option<&[u8]>, generated_document: &[u8], force: bool,
) -> Result<PlannedWrite, FenceError> {
    let generated =
        parse_document(generated_document)?.ok_or(FenceError::GeneratedDocumentMissingFences)?;

    let Some(existing) = existing else {
        return Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::Create,
        });
    };

    match parse_document(existing)? {
        Some(current) => {
            let mut bytes = Vec::with_capacity(
                current.prefix().len() + generated.generated_block().len() + current.suffix().len(),
            );
            bytes.extend_from_slice(current.prefix());
            bytes.extend_from_slice(generated.generated_block());
            bytes.extend_from_slice(current.suffix());
            let disposition = if bytes == existing {
                WriteDisposition::Unchanged
            } else {
                WriteDisposition::ReplaceFencedBlock
            };
            Ok(PlannedWrite { bytes, disposition })
        }
        None if force => Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::ForceRewriteUnfenced,
        }),
        None => Err(FenceError::ExistingUnfencedAgentsMd),
    }
}

fn parse_opening_metadata(
    bytes: &[u8], mut pos: usize,
) -> Result<(BTreeMap<String, String>, usize), FenceError> {
    ensure_opening_terminator_exists(bytes, pos)?;
    let mut metadata = BTreeMap::new();
    loop {
        let (line, next_pos) =
            read_line(bytes, pos).ok_or(FenceError::MissingOpeningFenceTerminator)?;
        if line == OPEN_END_LINE {
            if metadata.is_empty() {
                return Err(FenceError::MissingOpeningFenceMetadata);
            }
            return Ok((metadata, next_pos));
        }
        let (key, value) = parse_metadata_line(line)?;
        if metadata.insert(key.clone(), value).is_some() {
            return Err(FenceError::DuplicateMetadataKey(key));
        }
        pos = next_pos;
    }
}

fn ensure_opening_terminator_exists(bytes: &[u8], mut pos: usize) -> Result<(), FenceError> {
    loop {
        let (line, next_pos) =
            read_line(bytes, pos).ok_or(FenceError::MissingOpeningFenceTerminator)?;
        if line == OPEN_END_LINE {
            return Ok(());
        }
        if next_pos == bytes.len() {
            return Err(FenceError::MissingOpeningFenceTerminator);
        }
        pos = next_pos;
    }
}

fn parse_metadata_line(line: &[u8]) -> Result<(String, String), FenceError> {
    let Some(separator) = find_subslice(line, b": ", 0) else {
        return Err(invalid_metadata_line(line));
    };
    let key = &line[..separator];
    let value = &line[separator + 2..];
    if key.is_empty() || value.is_empty() || !key.iter().all(u8::is_ascii_lowercase_or_digit_hyphen)
    {
        return Err(invalid_metadata_line(line));
    }
    let key = String::from_utf8(key.to_vec()).map_err(|_err| invalid_metadata_line(line))?;
    let value = String::from_utf8(value.to_vec()).map_err(|_err| invalid_metadata_line(line))?;
    Ok((key, value))
}

fn invalid_metadata_line(line: &[u8]) -> FenceError {
    FenceError::InvalidMetadataLine(String::from_utf8_lossy(line).into_owned())
}

fn read_line(bytes: &[u8], start: usize) -> Option<(&[u8], usize)> {
    if start >= bytes.len() {
        return None;
    }
    let line = bytes[start..].iter().position(|byte| *byte == b'\n').map_or_else(
        || (&bytes[start..], bytes.len()),
        |relative_end| {
            let end = start + relative_end;
            (&bytes[start..end], end + 1)
        },
    );
    Some(line)
}

fn find_valid_closing_fences(bytes: &[u8], start: usize) -> Result<Vec<usize>, FenceError> {
    let mut positions = Vec::new();
    let mut cursor = start;
    while let Some(pos) = find_subslice(bytes, CLOSE_MARKER, cursor) {
        if is_line_start(bytes, pos) && is_line_end(bytes, pos + CLOSE_MARKER.len()) {
            positions.push(pos);
        }
        cursor = pos.checked_add(CLOSE_MARKER.len()).ok_or(FenceError::MissingClosingFence)?;
    }
    Ok(positions)
}

fn find_subslice(haystack: &[u8], needle: &[u8], start: usize) -> Option<usize> {
    if start > haystack.len() || needle.is_empty() {
        return None;
    }
    haystack[start..].windows(needle.len()).position(|pos| pos == needle).map(|pos| start + pos)
}

const fn is_line_start(bytes: &[u8], pos: usize) -> bool {
    pos == 0 || bytes[pos - 1] == b'\n'
}

const fn is_line_end(bytes: &[u8], pos: usize) -> bool {
    pos == bytes.len() || bytes[pos] == b'\n'
}

trait MetadataKeyByte {
    fn is_ascii_lowercase_or_digit_hyphen(&self) -> bool;
}

impl MetadataKeyByte for u8 {
    fn is_ascii_lowercase_or_digit_hyphen(&self) -> bool {
        self.is_ascii_lowercase() || self.is_ascii_digit() || *self == b'-'
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const GENERATED: &[u8] = b"# demo - Agent Instructions\n\n<!-- specify:context begin\nfingerprint: sha256:new\ngenerated-by: specify 0.2.0\n-->\n\n## Runtime\n- new\n\n<!-- specify:context end -->\n";

    fn fenced_existing() -> Vec<u8> {
        b"# hand title\n\n<!-- specify:context begin\nfingerprint: sha256:old\n-->\n\nold body\n\n<!-- specify:context end -->\n\noperator notes\n".to_vec()
    }

    #[test]
    fn parser_splits_fenced_document_and_metadata() {
        let input = fenced_existing();
        let parsed = parse_document(&input).expect("parse ok").expect("fences present");

        assert_eq!(parsed.prefix(), b"# hand title\n\n");
        assert_eq!(parsed.body(), b"\nold body\n\n");
        assert_eq!(parsed.suffix(), b"\n\noperator notes\n");
        assert_eq!(parsed.metadata().get("fingerprint").map(String::as_str), Some("sha256:old"));
        assert_eq!(
            parsed.generated_block(),
            b"<!-- specify:context begin\nfingerprint: sha256:old\n-->\n\nold body\n\n<!-- specify:context end -->"
        );
    }

    #[test]
    fn parser_returns_none_for_unfenced_document() {
        let parsed =
            parse_document(b"# hand-authored\n\nNo managed context here.\n").expect("parse ok");

        assert!(parsed.is_none());
    }

    #[test]
    fn parser_rejects_opening_fence_without_terminator() {
        let err = parse_document(b"<!-- specify:context begin\nfingerprint: sha256:test\nbody")
            .expect_err("unterminated fence must fail");

        assert_eq!(err, FenceError::MissingOpeningFenceTerminator);
    }

    #[test]
    fn parser_rejects_invalid_metadata_line() {
        let err = parse_document(
            b"<!-- specify:context begin\nfingerprint sha256:test\n-->\nbody\n<!-- specify:context end -->",
        )
        .expect_err("invalid metadata must fail");

        assert_eq!(err, FenceError::InvalidMetadataLine("fingerprint sha256:test".to_string()));
    }

    #[test]
    fn parser_rejects_opening_fence_without_metadata() {
        let err =
            parse_document(b"<!-- specify:context begin\n-->\nbody\n<!-- specify:context end -->")
                .expect_err("missing metadata must fail");

        assert_eq!(err, FenceError::MissingOpeningFenceMetadata);
    }

    #[test]
    fn parser_rejects_duplicate_metadata_key() {
        let err = parse_document(
            b"<!-- specify:context begin\nfingerprint: sha256:a\nfingerprint: sha256:b\n-->\nbody\n<!-- specify:context end -->",
        )
        .expect_err("duplicate metadata must fail");

        assert_eq!(err, FenceError::DuplicateMetadataKey("fingerprint".to_string()));
    }

    #[test]
    fn parser_rejects_closing_fence_with_trailing_space() {
        let err = parse_document(
            b"<!-- specify:context begin\nfingerprint: sha256:test\n-->\nbody\n<!-- specify:context end --> \n",
        )
        .expect_err("strict closing line must fail");

        assert_eq!(err, FenceError::MissingClosingFence);
    }

    #[test]
    fn parser_rejects_multiple_context_blocks() {
        let input = b"<!-- specify:context begin\nfingerprint: sha256:a\n-->\na\n<!-- specify:context end -->\n<!-- specify:context begin\nfingerprint: sha256:b\n-->\nb\n<!-- specify:context end -->";
        let err = parse_document(input).expect_err("multiple fences must fail");

        assert_eq!(err, FenceError::MultipleOpeningFences);
    }

    #[test]
    fn writer_creates_full_document_when_agents_is_absent() {
        let planned = plan_agents_write(None, GENERATED, false).expect("plan ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::Create);
    }

    #[test]
    fn writer_refuses_existing_unfenced_document_without_force() {
        let err = plan_agents_write(Some(b"# hand-authored\n"), GENERATED, false)
            .expect_err("unfenced must refuse");

        assert_eq!(err, FenceError::ExistingUnfencedAgentsMd);
    }

    #[test]
    fn writer_rewrites_existing_unfenced_document_with_force() {
        let planned = plan_agents_write(Some(b"# hand-authored\n"), GENERATED, true)
            .expect("force rewrite ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::ForceRewriteUnfenced);
    }

    #[test]
    fn writer_replaces_only_generated_block() {
        let existing = fenced_existing();
        let planned = plan_agents_write(Some(&existing), GENERATED, false).expect("plan ok");
        let expected = b"# hand title\n\n<!-- specify:context begin\nfingerprint: sha256:new\ngenerated-by: specify 0.2.0\n-->\n\n## Runtime\n- new\n\n<!-- specify:context end -->\n\noperator notes\n";

        assert_eq!(planned.bytes, expected);
        assert_eq!(planned.disposition, WriteDisposition::ReplaceFencedBlock);
    }

    #[test]
    fn writer_preserves_non_utf8_surrounding_bytes() {
        let existing = [
            b"prefix ".as_slice(),
            &[0xff, b'\n'],
            b"<!-- specify:context begin\nfingerprint: sha256:old\n-->\nold\n<!-- specify:context end -->",
            &[b'\n', 0xfe],
        ]
        .concat();
        let planned = plan_agents_write(Some(&existing), GENERATED, false).expect("plan ok");

        assert!(planned.bytes.starts_with(b"prefix \xff\n<!-- specify:context begin"));
        assert!(planned.bytes.ends_with(b"\n\xfe"));
    }

    #[test]
    fn writer_reports_unchanged_when_bytes_match() {
        let planned = plan_agents_write(Some(GENERATED), GENERATED, false).expect("plan ok");

        assert_eq!(planned.bytes, GENERATED);
        assert_eq!(planned.disposition, WriteDisposition::Unchanged);
    }

    #[test]
    fn writer_requires_generated_document_to_be_fenced() {
        let err = plan_agents_write(None, b"# generated but unfenced\n", false)
            .expect_err("generated document without fences must fail");

        assert_eq!(err, FenceError::GeneratedDocumentMissingFences);
    }
}
