//! Codegen for Vectis scaffold template registries from `templates/vectis/manifest.yaml`.

use std::collections::{BTreeSet, HashMap};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use jsonschema::Validator;
use serde::Deserialize;

const SCHEMA_VERSION: i64 = 1;
const INCLUDE_STR_PREFIX: &str = "../../../../../templates/vectis";
const EXPECTED_COUNTS: &[(&str, usize)] = &[("core", 13), ("ios", 7), ("android", 19)];
const ASSEMBLY_ORDER: &[&str] = &["core", "ios", "android"];
const MANIFEST_IGNORED: &str = "MANIFEST.md";

fn main() {
    if let Err(err) = run() {
        panic!("vectis template manifest codegen failed: {err}");
    }
}

fn run() -> Result<(), String> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|err| err.to_string())?);
    let repo_root = manifest_dir.join("../..");
    let templates_root = repo_root.join("templates/vectis");
    let manifest_path = templates_root.join("manifest.yaml");
    let schema_path = repo_root.join("schemas/vectis/template-manifest.schema.json");
    let registry_out =
        manifest_dir.join("src/scaffold/templates/registry.rs");

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", schema_path.display());

    let manifest_text =
        fs::read_to_string(&manifest_path).map_err(|err| format!("read {}: {err}", manifest_path.display()))?;
    let schema_text =
        fs::read_to_string(&schema_path).map_err(|err| format!("read {}: {err}", schema_path.display()))?;

    let manifest_value: serde_json::Value = serde_saphyr::from_str(&manifest_text)
        .map_err(|err| format!("parse {}: {err}", manifest_path.display()))?;
    validate_schema(&schema_text, &manifest_value)?;

    let manifest: Manifest = serde_saphyr::from_str(&manifest_text)
        .map_err(|err| format!("deserialize {}: {err}", manifest_path.display()))?;
    if manifest.schema_version != SCHEMA_VERSION {
        return Err(format!(
            "unsupported schema-version {} (expected {SCHEMA_VERSION})",
            manifest.schema_version
        ));
    }

    for (assembly, expected) in EXPECTED_COUNTS {
        let spec = manifest
            .assemblies
            .get(*assembly)
            .ok_or_else(|| format!("assemblies.{assembly} is missing"))?;
        if spec.files.len() != *expected {
            return Err(format!(
                "assemblies.{assembly} must list {expected} files, got {}",
                spec.files.len()
            ));
        }
        detect_orphans(assembly, &templates_root.join(assembly), spec)?;
    }

    let mut out = String::from("// @generated by build.rs — do not edit\n\n");
    for assembly in ASSEMBLY_ORDER {
        let spec = manifest
            .assemblies
            .get(*assembly)
            .ok_or_else(|| format!("assemblies.{assembly} is missing"))?;
        emit_assembly(&mut out, assembly, spec, &templates_root)?;
    }

    if let Some(parent) = registry_out.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    fs::write(&registry_out, out)
        .map_err(|err| format!("write {}: {err}", registry_out.display()))?;
    Ok(())
}

fn validate_schema(schema_text: &str, value: &serde_json::Value) -> Result<(), String> {
    let schema: serde_json::Value =
        serde_json::from_str(schema_text).map_err(|err| format!("parse schema JSON: {err}"))?;
    let validator = Validator::new(&schema).map_err(|err| format!("compile schema: {err}"))?;
    let mut details = String::new();
    for err in validator.iter_errors(value) {
        details.push_str(&format!("- {err}\n"));
    }
    if details.is_empty() {
        Ok(())
    } else {
        Err(format!("manifest.yaml failed schema validation:\n{details}"))
    }
}

fn detect_orphans(assembly: &str, assembly_dir: &Path, spec: &AssemblySpec) -> Result<(), String> {
    let listed: BTreeSet<String> = spec.files.iter().map(|entry| entry.source.clone()).collect();

    for entry in fs::read_dir(assembly_dir)
        .map_err(|err| format!("read {}: {err}", assembly_dir.display()))?
    {
        let entry = entry.map_err(|err| format!("read dir entry in {}: {err}", assembly_dir.display()))?;
        let file_name = entry.file_name();
        let name = file_name.to_string_lossy();
        if !entry.file_type().map_err(|err| format!("file type for {name}: {err}"))?.is_file() {
            continue;
        }
        if name == MANIFEST_IGNORED {
            continue;
        }
        if !listed.contains(name.as_ref()) {
            return Err(format!(
                "orphan template file {}/{} is not listed in manifest.yaml assemblies.{assembly}.files",
                assembly_dir.display(),
                name
            ));
        }
        println!("cargo:rerun-if-changed={}", entry.path().display());
    }

    for source in &listed {
        let path = assembly_dir.join(source);
        if !path.is_file() {
            return Err(format!(
                "manifest lists missing template source assemblies.{assembly}.files source={source:?} ({})",
                path.display()
            ));
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }
    Ok(())
}

fn emit_assembly(
    out: &mut String, assembly: &str, spec: &AssemblySpec, templates_root: &Path,
) -> Result<(), String> {
    out.push_str(&format!("pub(crate) mod {assembly} {{\n"));
    if spec.files.iter().any(|entry| entry.include_when.is_some()) {
        out.push_str("    use crate::scaffold::Capability;\n");
    }
    out.push_str("    use crate::scaffold::templates::{IncludeWhen, PathMode, TemplateEntry};\n\n");
    out.push_str("    pub(crate) const ENTRIES: &[TemplateEntry] = &[\n");

    for entry in &spec.files {
        let source_path = templates_root.join(assembly).join(&entry.source);
        if !source_path.is_file() {
            return Err(format!("missing template source: {}", source_path.display()));
        }
        let include_path = format!("{INCLUDE_STR_PREFIX}/{assembly}/{}", entry.source);
        out.push_str("        TemplateEntry {\n");
        out.push_str(&format!("            target: {:?},\n", entry.target));
        out.push_str(&format!("            contents: include_str!(\"{include_path}\"),\n"));
        out.push_str(&format!(
            "            path_mode: PathMode::{},\n",
            path_mode_rust(&spec.path_mode)
        ));
        out.push_str(&format!(
            "            include_when: {},\n",
            include_when_rust(entry.include_when.as_ref())
        ));
        out.push_str("        },\n");
    }

    out.push_str("    ];\n");
    out.push_str("}\n\n");
    Ok(())
}

fn path_mode_rust(path_mode: &str) -> &'static str {
    match path_mode {
        "content-only" => "ContentOnly",
        "app-name" => "AppName",
        "android-package" => "AndroidPackage",
        other => panic!("unsupported path-mode {other:?}"),
    }
}

fn include_when_rust(include_when: Option<&IncludeWhenSpec>) -> String {
    match include_when {
        None => "IncludeWhen::Always".to_string(),
        Some(spec) => {
            let caps: Vec<String> = spec
                .any_of
                .iter()
                .map(|tag| format!("Capability::{}", capability_variant(tag)))
                .collect();
            format!("IncludeWhen::AnyOf(&[{}])", caps.join(", "))
        }
    }
}

fn capability_variant(tag: &str) -> &'static str {
    match tag {
        "http" => "Http",
        "kv" => "Kv",
        "time" => "Time",
        "platform" => "Platform",
        "sse" => "Sse",
        other => panic!("unsupported capability tag {other:?}"),
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct Manifest {
    schema_version: i64,
    assemblies: HashMap<String, AssemblySpec>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct AssemblySpec {
    path_mode: String,
    files: Vec<FileEntry>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct FileEntry {
    source: String,
    target: String,
    include_when: Option<IncludeWhenSpec>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct IncludeWhenSpec {
    any_of: Vec<String>,
}
