// @generated by build.rs — do not edit

pub(crate) mod core {
    use crate::scaffold::templates::{IncludeWhen, PathMode, TemplateEntry};

    pub(crate) const ENTRIES: &[TemplateEntry] = &[
        TemplateEntry {
            target: "Cargo.toml",
            contents: include_str!("../../../../../templates/vectis/core/workspace-cargo.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "clippy.toml",
            contents: include_str!("../../../../../templates/vectis/core/clippy.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "rust-toolchain.toml",
            contents: include_str!("../../../../../templates/vectis/core/rust-toolchain.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: ".gitignore",
            contents: include_str!("../../../../../templates/vectis/core/gitignore"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "shared/Cargo.toml",
            contents: include_str!("../../../../../templates/vectis/core/shared-cargo.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "shared/src/lib.rs",
            contents: include_str!("../../../../../templates/vectis/core/lib.rs"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "shared/src/app.rs",
            contents: include_str!("../../../../../templates/vectis/core/app.rs"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "shared/src/ffi.rs",
            contents: include_str!("../../../../../templates/vectis/core/ffi.rs"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "shared/src/bin/codegen.rs",
            contents: include_str!("../../../../../templates/vectis/core/codegen.rs"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "deny.toml",
            contents: include_str!("../../../../../templates/vectis/core/deny.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "supply-chain/config.toml",
            contents: include_str!("../../../../../templates/vectis/core/supply-chain-config.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "supply-chain/audits.toml",
            contents: include_str!("../../../../../templates/vectis/core/supply-chain-audits.toml"),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "supply-chain/imports.lock",
            contents: include_str!(
                "../../../../../templates/vectis/core/supply-chain-imports.lock"
            ),
            path_mode: PathMode::ContentOnly,
            include_when: IncludeWhen::Always,
        },
    ];
}

pub(crate) mod ios {
    use crate::scaffold::templates::{IncludeWhen, PathMode, TemplateEntry};

    pub(crate) const ENTRIES: &[TemplateEntry] = &[
        TemplateEntry {
            target: "iOS/project.yml",
            contents: include_str!("../../../../../templates/vectis/ios/project.yml"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/Makefile",
            contents: include_str!("../../../../../templates/vectis/ios/Makefile"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/__APP_NAME__App.swift",
            contents: include_str!("../../../../../templates/vectis/ios/App.swift"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/Core.swift",
            contents: include_str!("../../../../../templates/vectis/ios/Core.swift"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/ContentView.swift",
            contents: include_str!("../../../../../templates/vectis/ios/ContentView.swift"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/Views/LoadingScreen.swift",
            contents: include_str!("../../../../../templates/vectis/ios/LoadingScreen.swift"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/Views/HomeScreen.swift",
            contents: include_str!("../../../../../templates/vectis/ios/HomeScreen.swift"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "iOS/__APP_NAME__/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json",
            contents: include_str!("../../../../../templates/vectis/ios/AppIcon-Contents.json"),
            path_mode: PathMode::AppName,
            include_when: IncludeWhen::Always,
        },
    ];
}

pub(crate) mod android {
    use crate::scaffold::Capability;
    use crate::scaffold::templates::{IncludeWhen, PathMode, TemplateEntry};

    pub(crate) const ENTRIES: &[TemplateEntry] = &[
        TemplateEntry {
            target: "Android/Makefile",
            contents: include_str!("../../../../../templates/vectis/android/Makefile"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/.gitignore",
            contents: include_str!("../../../../../templates/vectis/android/gitignore"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/build.gradle.kts",
            contents: include_str!("../../../../../templates/vectis/android/root-build.gradle.kts"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/settings.gradle.kts",
            contents: include_str!("../../../../../templates/vectis/android/settings.gradle.kts"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/gradle.properties",
            contents: include_str!("../../../../../templates/vectis/android/gradle.properties"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/gradle/libs.versions.toml",
            contents: include_str!("../../../../../templates/vectis/android/libs.versions.toml"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/build.gradle.kts",
            contents: include_str!("../../../../../templates/vectis/android/app-build.gradle.kts"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/shared/build.gradle.kts",
            contents: include_str!(
                "../../../../../templates/vectis/android/shared-build.gradle.kts"
            ),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/AndroidManifest.xml",
            contents: include_str!("../../../../../templates/vectis/android/AndroidManifest.xml"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/values/themes.xml",
            contents: include_str!("../../../../../templates/vectis/android/themes.xml"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/xml/network_security_config.xml",
            contents: include_str!(
                "../../../../../templates/vectis/android/network-security-config.xml"
            ),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::AnyOf(&[Capability::Http, Capability::Sse]),
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/__APP_NAME__Application.kt",
            contents: include_str!("../../../../../templates/vectis/android/Application.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/MainActivity.kt",
            contents: include_str!("../../../../../templates/vectis/android/MainActivity.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/core/Core.kt",
            contents: include_str!("../../../../../templates/vectis/android/Core.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/ui/screens/LoadingScreen.kt",
            contents: include_str!("../../../../../templates/vectis/android/LoadingScreen.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/ui/screens/HomeScreen.kt",
            contents: include_str!("../../../../../templates/vectis/android/HomeScreen.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/ui/theme/Color.kt",
            contents: include_str!("../../../../../templates/vectis/android/Color.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/ui/theme/Theme.kt",
            contents: include_str!("../../../../../templates/vectis/android/Theme.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/java/__ANDROID_PACKAGE_PATH__/ui/theme/Type.kt",
            contents: include_str!("../../../../../templates/vectis/android/Type.kt"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml",
            contents: include_str!("../../../../../templates/vectis/android/ic_launcher.xml"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml",
            contents: include_str!("../../../../../templates/vectis/android/ic_launcher_round.xml"),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/drawable/ic_launcher_foreground.xml",
            contents: include_str!(
                "../../../../../templates/vectis/android/ic_launcher_foreground.xml"
            ),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
        TemplateEntry {
            target: "Android/app/src/main/res/values/ic_launcher_background.xml",
            contents: include_str!(
                "../../../../../templates/vectis/android/ic_launcher_background.xml"
            ),
            path_mode: PathMode::AndroidPackage,
            include_when: IncludeWhen::Always,
        },
    ];
}
