#!/usr/bin/env bash
# Rebuild the WASI fixture components consumed by `tests/tool.rs`.
#
# These fixtures change rarely; the `.wasm` outputs are checked in
# under `tests/fixtures/tools-test-{project,cap}/wasm/`. Run this
# script whenever a fixture's Rust source or WAT changes, then
# commit the regenerated bytes.
#
# Requirements:
#   - `wasm32-wasip2` target installed (`rustup target add wasm32-wasip2`)
#   - `wasm-tools` on PATH (`cargo install wasm-tools`)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

CARGO_TARGET_DIR=target/tools-test-fixtures cargo build \
    --manifest-path tests/fixtures/tools-test-project/src-rust/Cargo.toml \
    --target wasm32-wasip2 \
    --release \
    --bins

mkdir -p tests/fixtures/tools-test-project/wasm tests/fixtures/tools-test-cap/wasm

for bin in echo read-only read-write read-denied; do
    cp "target/tools-test-fixtures/wasm32-wasip2/release/${bin}.wasm" \
        "tests/fixtures/tools-test-project/wasm/${bin}.wasm"
done

wasm-tools parse \
    tests/fixtures/tools-test-cap/src-wat/exit-seven.component.wat \
    -o tests/fixtures/tools-test-cap/wasm/exit-seven.wasm
