//! Project-topology resolution: normalise persisted project
//! configuration into the request envelope's `projects[]`.
//!
//! Unlike the pure assembly in [`super::catalog`], every branch here
//! touches the filesystem — the workspace branch reads the committed
//! `.specify/topology.lock`; the regular branch resolves the project's
//! target adapter under `project_dir`.

use std::path::{Path, PathBuf};

use specify_diagnostics::{Artifact, Diagnostic, DiagnosticKind, DiagnosticSource, Severity};
use specify_error::{Error, Result};

use super::wire::ProjectRef;
use crate::adapter::TargetAdapter;
use crate::config::{Layout, ProjectConfig};
use crate::init::adapter_name_from_value;
use crate::registry::catalog::Registry;
use crate::registry::topology::{Surface, TopologyLock};

/// Normalise persisted project configuration into the request's
/// `projects[]` topology.
///
/// Two branches, keyed on the workspace discriminator
/// ([`ProjectConfig::workspace`]):
///
/// - **Workspace** — one [`ProjectRef`] per entry in the committed
///   `.specify/topology.lock`, the projection of each member
///   project's `project.yaml` regenerated by `specify workspace sync`.
///   `name`, `target`, `description`, `surface[]`, `decisions[]`, and
///   `recent[]` come from the cache. An absent cache fails `topology-cache-missing`
///   directing the operator to run `workspace sync`.
/// - **Single regular project** — one synthesised [`ProjectRef`]:
///   `name` from `project.yaml.name`, `description` from `project.yaml`,
///   `target` formed by resolving `project.yaml.adapter` through
///   [`TargetAdapter::resolve`], plus the live baseline projection
///   (`surface[]`, `decisions[]`, `recent[]`). A regular project reads its
///   own `project.yaml` live as its single source of truth — no cache.
///
/// Both branches touch the filesystem: the workspace branch reads the lock,
/// the regular branch resolves the target adapter under `project_dir`.
///
/// # Errors
///
/// - [`Error::Validation`] (`topology-cache-missing`) when a workspace has no
///   committed `.specify/topology.lock`.
/// - [`Error::Validation`] (`plan-propose-project-adapter-missing`) when
///   a regular `project.yaml` omits `adapter` — a corrupt project that
///   `specify init` never produces.
/// - Any error from [`TargetAdapter::resolve`] (`adapter-not-found`,
///   `adapter-schema-violation`, …) when the regular project's adapter
///   cannot be resolved.
pub fn resolve_topology(config: &ProjectConfig, project_dir: &Path) -> Result<Vec<ProjectRef>> {
    if config.workspace {
        workspace_topology(project_dir)
    } else {
        regular_topology(config, project_dir).map(|project| vec![project])
    }
}

/// RFC-46 D6 — project greenfield-seed domains into seedless surfaces.
///
/// For each topology project that names a `registry.yaml` entry carrying a
/// non-empty `greenfield_seed.domains[]`, returning advisory
/// `greenfield-seed-shadowed` findings for seeds a baseline supersedes:
///
/// - **Greenfield** (`surface[]` empty *and* no `.specify/specs/`): the
///   seed domains project into `surface[]` as domains with empty
///   `requirements[]`, the greenfield analog of the baseline domain list,
///   so a fresh project still routes leads at plan time.
/// - **Shadowed** (`.specify/specs/` exists): the real surface supersedes
///   the seed, so the seed is ignored and a `greenfield-seed-shadowed`
///   info finding suggests removing the now-stale seed.
///
/// `workspace` selects where each project's `.specify/specs/` lives:
/// the project dir itself for a single regular project, or
/// `workspace/<name>/` for a workspace member.
#[must_use]
pub fn apply_greenfield_seed(
    topology: &mut [ProjectRef], registry: &Registry, project_dir: &Path, workspace: bool,
) -> Vec<Diagnostic> {
    let mut findings = Vec::new();
    for project in topology.iter_mut() {
        let Some(entry) = registry.projects.iter().find(|p| p.name == project.name) else {
            continue;
        };
        let Some(seed) = &entry.greenfield_seed else {
            continue;
        };
        if seed.domains.is_empty() {
            continue;
        }
        let has_baseline = project_specs_dir(project_dir, &project.name, workspace).is_dir();
        if has_baseline {
            findings.push(seed_shadowed_finding(&project.name));
        } else if project.surface.is_empty() {
            project.surface = seed
                .domains
                .iter()
                .map(|domain| Surface {
                    domain: domain.clone(),
                    requirements: Vec::new(),
                    more: None,
                })
                .collect();
        }
    }
    findings
}

/// Resolve a topology project's `.specify/specs/` directory: the project
/// dir itself for a regular project, `workspace/<name>/` for a workspace
/// member.
fn project_specs_dir(project_dir: &Path, name: &str, workspace: bool) -> PathBuf {
    let root =
        if workspace { project_dir.join("workspace").join(name) } else { project_dir.to_path_buf() };
    Layout::new(&root).specify_dir().join("specs")
}

/// Build one advisory `greenfield-seed-shadowed` info finding.
fn seed_shadowed_finding(project: &str) -> Diagnostic {
    let message = format!(
        "project '{project}' declares a greenfield_seed but already has a baseline \
         (.specify/specs/ exists); the real surface supersedes the seed — remove it from registry.yaml"
    );
    Diagnostic::finding(
        "greenfield-seed-shadowed".to_string(),
        message.clone(),
        message,
        Severity::Suggestion,
        DiagnosticKind::Review,
        DiagnosticSource::Deterministic,
        Artifact::Plan,
        None,
    )
}

/// Project every committed `.specify/topology.lock` entry into a
/// [`ProjectRef`]. Workspace topology is derived from each member
/// project's `project.yaml`, not from `registry.yaml`.
fn workspace_topology(project_dir: &Path) -> Result<Vec<ProjectRef>> {
    let path = Layout::new(project_dir).topology_lock_path();
    let lock = TopologyLock::load(&path)?.ok_or_else(|| {
        Error::validation_failed(
            "topology-cache-missing",
            "a workspace has a committed .specify/topology.lock",
            "workspace plan-time topology requires .specify/topology.lock; \
             run `specify workspace sync` to regenerate it",
        )
    })?;
    Ok(lock
        .projects
        .into_iter()
        .map(|project| ProjectRef {
            name: project.name,
            target: project.target,
            description: project.description,
            surface: project.surface,
            recent: project.recent,
            decisions: project.decisions,
            decisions_more: project.decisions_more,
            platforms: project.platforms,
        })
        .collect())
}

/// Synthesise the sole [`ProjectRef`] for a single regular project.
fn regular_topology(config: &ProjectConfig, project_dir: &Path) -> Result<ProjectRef> {
    let adapter_value = config.adapter.as_deref().ok_or_else(|| {
        Error::validation_failed(
            "plan-propose-project-adapter-missing",
            "a regular project.yaml declares an adapter",
            "non-workspace project.yaml omits the `adapter` field",
        )
    })?;
    let resolved = TargetAdapter::resolve(adapter_name_from_value(adapter_value), project_dir)?;
    let target = format!("{}@v{}", resolved.manifest.name, resolved.manifest.version);
    let projection = crate::registry::identity::project_baseline(project_dir)?;
    Ok(ProjectRef {
        name: config.name.clone(),
        target,
        description: config.description.clone(),
        surface: projection.surface,
        recent: projection.recent,
        decisions: projection.decisions,
        decisions_more: projection.decisions_more,
        platforms: config.platforms.clone(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::catalog::{GreenfieldSeed, RegistryProject};

    fn project_ref(name: &str, surface: Vec<Surface>) -> ProjectRef {
        ProjectRef {
            name: name.to_string(),
            target: "omnia@v1".to_string(),
            description: None,
            surface,
            recent: Vec::new(),
            decisions: Vec::new(),
            decisions_more: None,
            platforms: Vec::new(),
        }
    }

    fn registry_with_seed(name: &str, domains: &[&str]) -> Registry {
        Registry {
            version: 1,
            projects: vec![RegistryProject {
                name: name.to_string(),
                url: ".".to_string(),
                adapter: Some("omnia@v1".to_string()),
                description: None,
                contracts: None,
                greenfield_seed: Some(GreenfieldSeed {
                    domains: domains.iter().map(|d| (*d).to_string()).collect(),
                }),
            }],
        }
    }

    #[test]
    fn seed_projects_into_empty_greenfield_surface() {
        let dir = tempfile::tempdir().expect("tempdir");
        let mut topology = vec![project_ref("svc", Vec::new())];
        let registry = registry_with_seed("svc", &["identity", "billing"]);

        let findings = apply_greenfield_seed(&mut topology, &registry, dir.path(), false);

        assert!(findings.is_empty(), "no baseline means no shadow finding");
        let domains: Vec<&str> =
            topology[0].surface.iter().map(|s| s.domain.as_str()).collect();
        assert_eq!(domains, ["identity", "billing"]);
        assert!(
            topology[0].surface.iter().all(|s| s.requirements.is_empty()),
            "seeded domains carry empty requirements"
        );
    }

    #[test]
    fn seed_is_shadowed_once_baseline_exists() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::create_dir_all(dir.path().join(".specify/specs/identity")).expect("specs");
        let existing = vec![Surface {
            domain: "identity".to_string(),
            requirements: vec!["Sign in".to_string()],
            more: None,
        }];
        let mut topology = vec![project_ref("svc", existing.clone())];
        let registry = registry_with_seed("svc", &["billing"]);

        let findings = apply_greenfield_seed(&mut topology, &registry, dir.path(), false);

        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].rule_id.as_deref(), Some("greenfield-seed-shadowed"));
        assert_eq!(topology[0].surface, existing, "real surface supersedes the seed");
    }

    #[test]
    fn absent_seed_is_a_noop() {
        let dir = tempfile::tempdir().expect("tempdir");
        let mut topology = vec![project_ref("svc", Vec::new())];
        let registry = Registry {
            version: 1,
            projects: Vec::new(),
        };

        let findings = apply_greenfield_seed(&mut topology, &registry, dir.path(), false);

        assert!(findings.is_empty());
        assert!(topology[0].surface.is_empty());
    }
}
