//! Project-topology resolution: normalise persisted project
//! configuration into the request envelope's `projects[]` (RFC-29 D2,
//! RFC-36).
//!
//! Unlike the pure assembly in [`super::catalog`], every branch here
//! touches the filesystem — the workspace branch reads the committed
//! `.specify/topology.lock`; the regular branch resolves the project's
//! target adapter under `project_dir`.

use std::path::Path;

use specify_error::{Error, Result};

use super::wire::ProjectRef;
use crate::adapter::TargetAdapter;
use crate::config::{Layout, ProjectConfig};
use crate::init::adapter_name_from_value;
use crate::registry::topology::TopologyLock;

/// Normalise persisted project configuration into the request's
/// `projects[]` topology.
///
/// Two branches, keyed on the workspace discriminator
/// ([`ProjectConfig::workspace`]):
///
/// - **Workspace** — one [`ProjectRef`] per entry in the committed
///   `.specify/topology.lock` (RFC-36), the projection of each member
///   project's `project.yaml` regenerated by `specify workspace sync`.
///   `name`, `target`, `description`, `surface[]`, `decisions[]`, and
///   `recent[]` come from the cache. An absent cache fails `topology-cache-missing`
///   directing the operator to run `workspace sync`.
/// - **Single regular project** — one synthesised [`ProjectRef`]:
///   `name` from `project.yaml.name`, `description` from `project.yaml`,
///   `target` formed by resolving `project.yaml.adapter` through
///   [`TargetAdapter::resolve`], plus the live baseline projection
///   (`surface[]`, `decisions[]`, `recent[]`). A regular project reads its
///   own `project.yaml` live as its single source of truth — no cache.
///
/// Both branches touch the filesystem: the workspace branch reads the lock,
/// the regular branch resolves the target adapter under `project_dir`.
///
/// # Errors
///
/// - [`Error::Validation`] (`topology-cache-missing`) when a workspace has no
///   committed `.specify/topology.lock`.
/// - [`Error::Validation`] (`plan-propose-project-adapter-missing`) when
///   a regular `project.yaml` omits `adapter` — a corrupt project that
///   `specify init` never produces.
/// - Any error from [`TargetAdapter::resolve`] (`adapter-not-found`,
///   `adapter-schema-violation`, …) when the regular project's adapter
///   cannot be resolved.
pub fn resolve_topology(config: &ProjectConfig, project_dir: &Path) -> Result<Vec<ProjectRef>> {
    if config.workspace {
        workspace_topology(project_dir)
    } else {
        regular_topology(config, project_dir).map(|project| vec![project])
    }
}

/// Project every committed `.specify/topology.lock` entry into a
/// [`ProjectRef`]. RFC-36: workspace topology is derived from each member
/// project's `project.yaml`, not from `registry.yaml`.
fn workspace_topology(project_dir: &Path) -> Result<Vec<ProjectRef>> {
    let path = Layout::new(project_dir).topology_lock_path();
    let lock = TopologyLock::load(&path)?.ok_or_else(|| {
        Error::validation_failed(
            "topology-cache-missing",
            "a workspace has a committed .specify/topology.lock",
            "workspace plan-time topology requires .specify/topology.lock; \
             run `specify workspace sync` to regenerate it",
        )
    })?;
    Ok(lock
        .projects
        .into_iter()
        .map(|project| ProjectRef {
            name: project.name,
            target: project.target,
            description: project.description,
            surface: project.surface,
            recent: project.recent,
            decisions: project.decisions,
            decisions_more: project.decisions_more,
            platforms: project.platforms,
        })
        .collect())
}

/// Synthesise the sole [`ProjectRef`] for a single regular project.
fn regular_topology(config: &ProjectConfig, project_dir: &Path) -> Result<ProjectRef> {
    let adapter_value = config.adapter.as_deref().ok_or_else(|| {
        Error::validation_failed(
            "plan-propose-project-adapter-missing",
            "a regular project.yaml declares an adapter",
            "non-workspace project.yaml omits the `adapter` field",
        )
    })?;
    let resolved = TargetAdapter::resolve(adapter_name_from_value(adapter_value), project_dir)?;
    let target = format!("{}@v{}", resolved.manifest.name, resolved.manifest.version);
    let projection = crate::registry::identity::project_baseline(project_dir)?;
    Ok(ProjectRef {
        name: config.name.clone(),
        target,
        description: config.description.clone(),
        surface: projection.surface,
        recent: projection.recent,
        decisions: projection.decisions,
        decisions_more: projection.decisions_more,
        platforms: config.platforms.clone(),
    })
}
